### ISSUE TITLE
Pools tab failing to load

### ISSUE THREAD

**Issue by Mutaru16bit** [clragon/e1547#81] opened 2022-10-20 23:09 UTC
Pools tab fails to load and it gives this in the log

`type 'Null' is not a subtype of type 'bool' in type cast`

`#0      _$$_PoolFromJson (package:e1547/pool/data/pool.g.dart:18)
#1      new _$_Pool.fromJson (package:e1547/pool/data/pool.freezed.dart:251)
#2      _$PoolFromJson (package:e1547/pool/data/pool.freezed.dart:18)
#3      new Pool.fromJson (package:e1547/pool/data/pool.dart:23)
#4      Client.pools (package:e1547/client/data/client.dart:336)
<asynchronous suspension>
#5      RawDataController.loadPage.<anonymous closure> (package:e1547/interface/data/controller.dart:166)
<asynchronous suspension>
#6      PageLock.protect (package:e1547/interface/data/controller.dart:320)
<asynchronous suspension>
#7      RawDataController.loadPage (package:e1547/interface/data/controller.dart:160)
<asynchronous suspension>`

**Comment by clragon** [comment] 2022-10-21 02:25
Thank you for reporting this. 
This issue is caused by the e621 API changing and consequently breaking how the app parses the API responses.
I will probably release a patch soon.

**Comment by clragon** [comment] 2022-10-25 14:51
fixed in 13.0.1

**Closed by clragon** 2022-10-25 14:51 UTC
