### ISSUE TITLE
editing a follow doesn't work

### ISSUE THREAD

**Issue by TayIorRobinson** [clragon/e1547#98] opened 2023-04-30 20:47 UTC
when you edit a follow, clicking the save button brings up the "Add to follow" bar instead of saving

**Comment by clragon** [comment] 2023-05-01 17:33
I cannot reproduce this. Can you provide reproduction steps?

**Comment by TayIorRobinson** [comment] 2023-05-02 20:21
https://user-images.githubusercontent.com/74316107/235777116-42b7d14f-22f0-4ace-9423-bfead30e753f.mp4

**Comment by clragon** [comment] 2023-05-06 14:51
error log:

```
Critical | 16:49:33.541 | Flutter: RangeError (index): Invalid value: Valid value range is empty: 0
╔ Error ═══════════════════════════════════════════════════════════════════════════════════╗
║
║  #0      _StringBase.[] (dart:core-patch/string_patch.dart:258:41)
║  #1      _TagInputState.build.<anonymous closure> (package:e1547/tag/widgets/input.dart:86:54)
║  #2      _TypeAheadFieldState._initOverlayEntry.<anonymous closure>.<anonymous closure> (package:flutter_typeahead/src/material/field/typeahead_field.dart:765:40)
║  #3      _SuggestionsListState.createSuggestionsWidget.<anonymous closure>.<anonymous closure> (package:flutter_typeahead/src/material/suggestions_box/suggestions_list.dart:395:43)
║  
║
╚══════════════════════════════════════════════════════════════════════════════════════════╝
```

**Comment by clragon** [comment] 2023-05-06 17:47
thank you, this has been fixed in the new version.
also note that as a workaround, you can press enter.

**Closed by clragon** 2023-05-06 17:47 UTC
Labels: bug
